### PR TITLE
Phase 1 of rk_stratiform CCPPization; CCPPize cldfrc; RK interstitials

### LINKED ISSUE #225: MUSICA GitHub actions test failing
Will be resolved in #219, this is an issue to document that the fix will be included in that PR.

@nusbaume wrote:
> Also, just an FYI that I believe you can fix the failing MUSICA tests by replacing CCPPStandardNames in the path to the script with ESMStandardNames, but if that doesn't work please let me know. Thanks!

and the path to the script was also updated to `ccpp_meta_stdname_check.py`.

### PR DESCRIPTION
**Pull request by jimmielin**
Originator(s): @jimmielin

Description (include issue title and the keyword ['closes', 'fixes', 'resolves'] and issue number):
- Partial CCPPization work of rk_stratiform (CAM4 microphysics and macrophysics) - #190, including:
- Cloud sedimentation `cloud_particle_sedimentation` (from `src/physics/cam/pkg_cld_sediment.F90`)
- Prognostic cloud water `prognostic_cloud_water` (`pcond` from `src/physics/cam/cldwat.F90`)
- Most interstitial code in `rk_stratiform_tend` moved to `rk_stratiform_*` interstitial schemes
- CCPPization of `compute_cloud_fraction` (`cldfrc` in `src/physics/cam/cloud_fraction.F90`); separating out `shallowcu` and `deepcu` and `concld` computation to `convective_cloud_cover` CCPPized scheme. This is used in CAM4 and CAM5
- Dechunkize and move to `to_be_ccppized/cloud_optical_properties.F90` several cloud optical property functions to `src/physics/cam/pkg_cldoptics.F90`: this is used in several cloud diagnostics in CAM.
- Fixes #225 

This code is not fully ready for use in SIMA in the current state. This is a first stage cleanup to move as much of rk_stratiform_tend code to atmospheric_physics as possible, before completing CCPPization. Thus the following changes are not in the scope of this PR (although reasonable effort has been made to complete these as much as possible):
* Completing metadata for use in CAM-SIMA
* Finalize standard names
* Create diagnostic schemes that correspond to existing diagnostics provided in CAM4
* Create test cases for FPHYStest with rasch_kristjansson SDF

Companion PR in ESCOMP/CAM: https://github.com/ESCOMP/CAM/pull/1271

List all namelist files that were added or changed:
```
A       schemes/cloud_fraction/compute_cloud_fraction_namelist.xml
A       schemes/cloud_fraction/convective_cloud_cover_namelist.xml
A       schemes/rasch_kristjansson/cloud_particle_sedimentation_namelist.xml
A       schemes/rasch_kristjansson/prognostic_cloud_water_namelist.xml
  - CCPPize cldfrc; cldwat; rk_stratiform_tend;

M       schemes/zhang_mcfarlane/zm_conv_options_namelist.xml
  - Remove cam6 phys_suite namelist defaults from SIMA

```

List all files eliminated and why: N/A

List all files added and what they do:
```
A       schemes/cloud_fraction/compute_cloud_fraction.F90
A       schemes/cloud_fraction/compute_cloud_fraction.meta
A       schemes/cloud_fraction/convective_cloud_cover.F90
A       schemes/cloud_fraction/convective_cloud_cover.meta
 - CCPPize cldfrc

A       schemes/rasch_kristjansson/cloud_particle_sedimentation.F90
A       schemes/rasch_kristjansson/cloud_particle_sedimentation.meta
 - CCPPize former `pkg_cld_sediment`

A       schemes/rasch_kristjansson/prognostic_cloud_water.F90
A       schemes/rasch_kristjansson/prognostic_cloud_water.meta
 - CCPPize former `cldwat`

A       schemes/rasch_kristjansson/rk_stratiform.F90
A       schemes/rasch_kristjansson/rk_stratiform.meta
 - Move most interstitial code in rk_stratiform_tend to individual CCPPized schemes

A       test/test_suites/suite_rasch_kristjansson.xml
 - Draft rk_stratiform_tend SDF

A       to_be_ccppized/cloud_optical_properties.F90
 - Dechunkized and moved from `pkg_cldoptics.F90`
```

List all existing files that have been modified, and describe the changes: 
(Helpful git command: `git diff --name-status development...<your_branch_name>`)
```
M       schemes/zhang_mcfarlane/zm_conv_options_namelist.xml
  - Remove cam6 phys_suite namelist defaults from SIMA

M       schemes/cloud_fraction/set_cloud_fraction_top.F90
M       schemes/dry_adiabatic_adjust/dadadj_namelist.xml
M       schemes/hack_shallow/convect_shallow_sum_to_deep.F90
M       schemes/hack_shallow/hack_convect_shallow.F90
M       schemes/hack_shallow/set_general_conv_fluxes_to_shallow.F90
M       schemes/hack_shallow/set_shallow_conv_fluxes_to_general.F90
  - Remove license headers in favor of LICENSE file in repo
```

List all automated tests that failed, as well as an explanation for why they weren't fixed: N/A

Is this an answer-changing PR? If so, is it a new physics package, algorithm change, tuning change, etc?

B4B for non-CAM4 regression tests and most CAM4 tests.

If all CAM4 diagnostics are enabled, there are two history fields (`HPROGCLD` and `HREPART`) that have roundoff level differences in the order of 1e-17 ~ 1e-16 due to rearranging of terms to compute diagnostics.

The change in heat flux computation and the subsequent roundoff difference will lead to some CAM4 tests to fail due to chaos. See detailed analysis in https://github.com/ESCOMP/CAM/pull/1271#issuecomment-2718680480

Not fully complete for use in SIMA in current state

If yes to the above question, describe how this code was validated with the new/modified features:

Validation is made as part of ESCOMP/CAM PR - https://github.com/ESCOMP/CAM/pull/1271

### CODE REVIEW

File: schemes/rasch_kristjansson/rk_stratiform.F90 [hunk 1]
```diff
@@ -0,0 +1,571 @@
...
+  use ccpp_kinds, only: kind_phys
+
+  implicit none
+  private
+  save
+
+  ! public CCPP-compliant subroutines
+  !   note: cloud_fraction_perturbation_run is NOT a fully CCPP-compliant scheme
+  !         because it calls the compute_cloud_fraction scheme for perturbation.
+  !         this is currently not possible to elegantly handle in the framework.
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/rk_stratiform.F90:16]: Can you elaborate on this?  My understanding is that listing `compute_cloud_fraction` as a dependency in the metadata file is a valid CCPP action, and should help enforce the fact that `compute_cloud_fraction` is required for `cloud_fraction_perturbation_run` even if not specifically listed in the SDF.  Is my understanding incorrect here, or am I just not understanding the core issue?

File: schemes/rasch_kristjansson/rk_stratiform.F90 [hunk 2]
```diff
@@ -0,0 +1,571 @@
...
+    errmsg, errflg)
+
+    ! Output arguments
+    character(len=512), intent(out)   :: errmsg         ! error message
+    integer,            intent(out)   :: errflg         ! error flag
+
+    errmsg = ''
+    errflg = 0
+
+  end subroutine rk_stratiform_init
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/rk_stratiform.F90:50]: Is this subroutine actually needed?  I don't believe the CCPP has a requirement for an `init` phase.

File: schemes/rasch_kristjansson/rk_stratiform.F90 [hunk 3]
```diff
@@ -0,0 +1,571 @@
...
+    character(len=512), intent(out)   :: errmsg         ! error message
+    integer,            intent(out)   :: errflg         ! error flag
+
+    errmsg = ''
+    errflg = 0
+
+    ! Check that qcwat and tcwat were initialized - if not then initialize
+    ! this is made as a separate "run" scheme so it does not have to be used in current CAM
+
+    ! The registry will set default values of negative if not read from snapshot.
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/rk_stratiform.F90:83]: Minor grammar fix:

```suggestion
    ! The registry will set default negative values if not read from snapshot.
```

File: schemes/rasch_kristjansson/rk_stratiform.F90 [hunk 4]
```diff
@@ -0,0 +1,571 @@
...
+
+    if(tcwat(1,1) < 0._kind_phys) then
+      tcwat(:ncol,:) = t(:ncol,:)
+    endif
+
+    ! lcwat is initialized from initial conditions of cldice, cldliq
+    ! TODO: check if this is always done (appears to be from physpkg.F90) or should be read from snapshot.
+    if(qcwat(1,1) < 0._kind_phys .or. tcwat(1,1) < 0._kind_phys) then
+      lcwat(:ncol,:) = cldice(:ncol,:) + cldliq(:ncol,:)
+    endif
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/rk_stratiform.F90:96]: Looking at the logic above won't this if-statement always be false assuming `q_wv` and `t` have valid values?

File: schemes/rasch_kristjansson/rk_stratiform.meta [hunk 5]
```diff
@@ -0,0 +1,887 @@
...
+  dimensions = (horizontal_loop_extent)
+  intent = in
+[ prec_sed ]
+  standard_name = stratiform_cloud_water_surface_flux_due_to_sedimentation
+  units = m s-1
+  type = real | kind = kind_phys
+  dimensions = (horizontal_loop_extent)
+  intent = out
+[ prec_str ]
+  standard_name = stratiform_rain_and_snow_surface_flux
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/rk_stratiform.meta:130]: I believe the standard name for this should probably be:

```suggestion
  standard_name = lwe_large_scale_precipitation_rate_at_surface
```

You could replace `large_scale` with `stratiform` if you want (they tend to be used interchangeably, at least in GCM-world).

**Review by nusbaume — CHANGES_REQUESTED** [review]
Thanks for all of the hard work @jimmielin!  I do have some change requests, but hopefully none of them take too much effort (if they do please let me know)!

Also, just an FYI that I believe you can fix the failing MUSICA test by replacing `CCPPStandardNames` in the path to the script with `ESMStandardNames`, but if that doesn't work please let me know.  Thanks!

File: schemes/rasch_kristjansson/rk_stratiform.F90 (hunk 1 above)
Comment (gold2718) [reply schemes/rasch_kristjansson/rk_stratiform.F90:16]: Is there a decision somewhere that a CCPP-compliant scheme cannot also be a utility (i.e.,subroutine registered in the metadata as a dependency)?

File: schemes/rasch_kristjansson/prognostic_cloud_water.F90 [hunk 6]
```diff
@@ -200,9 +200,9 @@ subroutine prognostic_cloud_water_init( &
     ciautb = 5.e-4_kind_phys
 
     if(amIRoot) then
-      write(iulog,*) 'tuning parameters prognostic_cloud_water_init: capnw',capnw,'capnc',capnc,'capnsi',capnsi,'kconst',kconst
-      write(iulog,*) 'tuning parameters prognostic_cloud_water_init: effc',effc,'alpha',alpha,'capc',capc
-      write(iulog,*) 'tuning parameters prognostic_cloud_water_init: critpr',critpr,'convfw',convfw,'cracw',cracw,'ciautb',ciautb
+      write(iulog,*) 'tuning parameters prognostic_cloud_water_init: capnw ',capnw,' capnc ',capnc,' capnsi ',capnsi,' kconst',kconst
```
Comment (nusbaume) [inline schemes/rasch_kristjansson/prognostic_cloud_water.F90:203]: Looks like one white space addition was missed:

```suggestion
      write(iulog,*) 'tuning parameters prognostic_cloud_water_init: capnw ',capnw,' capnc ',capnc,' capnsi ',capnsi,' kconst ',kconst
```

**Review by nusbaume — CHANGES_REQUESTED** [review]
Super close!  Just a few last whitespace change requests.

File: schemes/cloud_fraction/compute_cloud_fraction_namelist.xml [hunk 7]
```diff
@@ -3,46 +3,121 @@
...
     <desc>
       Turn on ice cloud fraction calculation
-      Default: TRUE (CAM5 and CAM6) or FALSE
+      Default: TRUE (CAM5, 6, 7) or FALSE
     </desc>
     <values>
-      <value>false</value>
+      <value>.false.</value>
+      <value phys_suite="cam7">.true.</value>
+      <value phys_suite="cam6">.true.</value>
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply schemes/cloud_fraction/compute_cloud_fraction_namelist.xml]: Removing it from ZM would be great, thanks!

File: schemes/rasch_kristjansson/rk_stratiform.F90 (hunk 1 above)
Comment (nusbaume) [reply schemes/rasch_kristjansson/rk_stratiform.F90:16]: I think for now I would vote to just remove the "not CCPP compliant" comment, as technically the scheme will still be portable even with the dependency (which is usually my definition of whether something is "compliant" or not).  We can certainly revisit this in the future if we think the way it is currently organized is not ideal.  Thanks!

**Review by nusbaume — APPROVED** [review]
Everything looks good to me now.  Thanks again @jimmielin!

**Review by cacraigucar — CHANGES_REQUESTED** [review]
While there a good number of requests, I don't think there is anything too time consuming and nothing fundamentally wrong.

File: schemes/cloud_fraction/compute_cloud_fraction.F90 [hunk 8]
```diff
@@ -0,0 +1,576 @@
...
+  real(kind_phys) :: icecrit           ! critical RH for ice clouds in Wilson and Ballard closure (smaller = more ice clouds)
+
+  ! flags
+  logical         :: inversion_cld_off ! turn off stratification-based cloud fraction (inversion_cld)
+
+  integer         :: k700              ! model level nearest to 700 mb [index]
+
+  ! constants
+  real(kind_phys), parameter :: pnot = 1.e5_kind_phys    ! reference pressure [Pa]
+  real(kind_phys), parameter :: lapse = 6.5e-3_kind_phys ! U.S. Standard Atmosphere lapse rate [K m-1]
```
[the remark this answers is not in the document]
Comment (cacraigucar) [reply schemes/cloud_fraction/compute_cloud_fraction.F90]: Do you need me to keep this unresolved?  (I'm not sure what the CAM patch is that you are referring to)

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: schemes/rasch_kristjansson/cloud_particle_sedimentation.meta [hunk 9]
```diff
@@ -0,0 +1,257 @@
...
+  type = real | kind = kind_phys
+  dimensions = (horizontal_loop_extent, vertical_interface_dimension)
+  intent = out
+[ liqtend ]
+  standard_name = tendency_of_cloud_liquid_water_mixing_ratio_wrt_moist_air_and_condensed_water
+  units = kg kg-1 s-1
+  type = real | kind = kind_phys
+  dimensions = (horizontal_loop_extent, vertical_layer_dimension)
+  intent = out
+  constituent = True
```
[the remark this answers is not in the document]
Comment (peverwhee) [reply schemes/rasch_kristjansson/cloud_particle_sedimentation.meta:213]: `constituent = True` works!
