### PR TITLE
Move nswbands, nlwbands to host namelist; initialize number concentration species in initialize_constituents

### LINKED ISSUE #332: qmin for chemistry/aerosol species read in from snapshot are incorrectly initialized in initialize_constituents
This code in current CAM, src/chemistry/mozart/chemistry.F90
```fortran
       qmin = 1.e-36_r8
...
       if ( lng_name(1:5) .eq. 'num_a' ) then ! aerosol number density
          qmin = 1.e-5_r8
       else if ( m == o3_ndx ) then
          qmin = 1.e-12_r8
       else if ( m == ch4_ndx ) then
          qmin = 1.e-12_r8
       else if ( m == n2o_ndx ) then
          qmin = 1.e-15_r8
       else if( m == cfc11_ndx .or. m == cfc12_ndx ) then
          qmin = 1.e-20_r8
       else if( m == o2_1s_ndx .or. m == o2_1d_ndx ) then
```

is not handled in `initialize_constituents` scheme, resulting in answer changes due to a different `qmin`. Currently, `initialize_constituents` initializes `qmin` for all species as `0.0_kind_phys`

This will have to be resolved in two places:
1. for snapshot runs, `initialize_constituents` needs to replicate the above logic, and
2. when chemistry constituents are actually initialized for a real model run (not in this issue)

I will work on (1) which is the scope of the issue here, as part of the UW PBL scheme work

cc @peverwhee

### PR DESCRIPTION
**Pull request by jimmielin**
Tag name (The PR title should also include the tag name):
Originator(s): @jimmielin 

Description (include issue title and the keyword ['closes', 'fixes', 'resolves'] and issue number):
- Moves `nswbands`, `nlwbands` to host-side radiation_namelist (CAM-SIMA companion PR: https://github.com/ESCOMP/CAM-SIMA/pull/493)
- Closes #332
- Initializes number concentration species (NUMLIQ, NUMICE, ...) in the test `initialize_constituents.F90` scheme.

List all namelist files that were added or changed:
```
M       schemes/rrtmgp/rrtmgp_pre_namelist.xml
  - moved nlwbands, nswbands to host-side (no effect on CAM)
```

List all files eliminated and why:

List all files added and what they do:

List all existing files that have been modified, and describe the changes:
(Helpful git command: `git diff --name-status development...<your_branch_name>`)
```
M       schemes/rrtmgp/rrtmgp_pre_namelist.xml
  - moved nlwbands, nswbands to host-side (no effect on CAM)
  
M       test/test_schemes/initialize_constituents.F90
  - add number concentration species standard names and logic
  - set qmin for chemistry species based on mozart initialization in CAM.
```

List all automated tests that failed, as well as an explanation for why they weren't fixed:

Is this an answer-changing PR? If so, is it a new physics package, algorithm change, tuning change, etc?

If yes to the above question, describe how this code was validated with the new/modified features:

### CODE REVIEW

File: test/test_schemes/initialize_constituents.F90 [hunk 1]
```diff
@@ -53,6 +55,12 @@ subroutine initialize_constituents_register(constituents, errmsg, errcode)
                                         'cnst_NUMICE', &
                                         'cnst_NUMSNO', &
                                         'cnst_NUMGRA'/)
+    character(len=75), parameter :: water_species_number_std_names(5) = &
+      (/'mass_number_concentration_of_cloud_liquid_wrt_moist_air_and_condensed_water', &
+        'mass_number_concentration_of_rain_wrt_moist_air_and_condensed_water        ', &
+        'mass_number_concentration_of_ice_wrt_moist_air_and_condensed_water         ', &
+        'mass_number_concentration_of_snow_wrt_moist_air_and_condensed_water        ', &
+        'mass_number_concentration_of_graupel_wrt_moist_air_and_condensed_water     '/)
```
Comment (nusbaume) [inline test/test_schemes/initialize_constituents.F90]: Total nit-pick, but I think for modern (2003) Fortran square brackets are recommended for parameter arrays:


```suggestion
      ['mass_number_concentration_of_cloud_liquid_wrt_moist_air_and_condensed_water', &
        'mass_number_concentration_of_rain_wrt_moist_air_and_condensed_water        ', &
        'mass_number_concentration_of_ice_wrt_moist_air_and_condensed_water         ', &
        'mass_number_concentration_of_snow_wrt_moist_air_and_condensed_water        ', &
        'mass_number_concentration_of_graupel_wrt_moist_air_and_condensed_water     ']
```

The same request holds for the other declared parameter arrays above as well.

File: test/test_schemes/initialize_constituents.F90 [hunk 2]
```diff
@@ -133,17 +153,42 @@ subroutine initialize_constituents_register(constituents, errmsg, errcode)
...
              min_value = 0.0_kind_phys,                 &
              advected = .true.,                         &
-             diag_name = const_diag_names(var_index),   & 
+             diag_name = const_diag_names(var_index),   &
              mixing_ratio_type = 'wet',                 &
              errcode = errcode,                         &
              errmsg = errmsg)
        else
+          ! For chemistry species some special handling is necessary for qmin_value;
+          ! this logic is replicated from chem_register in src/chemistry/mozart.
```
Comment (nusbaume) [inline test/test_schemes/initialize_constituents.F90]: I would make it clear that this is in reference to CAM:


```suggestion
          ! this logic is replicated from chem_register in src/chemistry/mozart in CAM.
```

**Review by nusbaume — APPROVED** [review]
Thanks @jimmielin! I have a couple nit-picky requests, but nothing is critical.

**Review by peverwhee — APPROVED** [review]
